### ISSUE TITLE
Getting error Can't resolve 'https'

### ISSUE THREAD

**Issue by k1muza** [marchitos/sportmonks#3]
I am trying to use the API on an Angular 6 app. I am getting this error

ERROR in ./node_modules/sportmonks/dist/sportmonks.class.js
Module not found: Error: Can't resolve 'https' in '/home/ubuntu/workspace/node_modules/sportmonks/dist'

**Comment by marchitos** [comment]
This API is designed to work with Node.js (I will add more info in the readme about that).
The required https module is native on node.
